### ISSUE TITLE
Odd behavior with "/foo"

### ISSUE THREAD

**Issue by robogeek** [jy95/path-directories#1]
I'm trying this module out - it is exactly what I was looking for, and was incredibly hard to find.  

In any case this result is rather strange.  I don't understand why getting the directories for `/foo` would return an array of two empty strings.

```
> const pd = require('path-directories');
> pd('/foo');
[ '', '' ]
```

**Comment by jy95** [comment]
Hello,

Originally , this was a quick test projet to see how to manipulate Node Api to get that information.
Thanks to recall me this : It was the bug I wanted to fix but I was too lazy after others projets and exams ^^

The bug was caused by these lines :
```
let dirname = require("path").dirname;
getDirnames = (path) => dirname(path); 
```
In short, "/foo" got extracted as "/" and then the split function causes to have 2 empty strings

I fixed this (v1.0.1) with a proper code (at 3 AM XD) so feel free to test it.
